[options]
; Өгөгдлийн сангийн тохиргоо
db_host = False
db_port = False
db_user = odoo
db_password = odoo

; Замуудын тохиргоо
; odoo/addons - Үндсэн модулиуд
; odoo/odoo/addons - Системийн модулиуд
; custom_addons - Таны өөрийн модулиуд
addons_path = odoo/addons, odoo/odoo/addons, custom_addons

; Порт
http_port = 8069